library(tidyverse)
library(keras3)
suppressMessages(library(tensorflow))
library(tidymodels)
library(rsample)
source("functions/readFiles.R")
source("functions/bakeFiles.R")
source("functions/rocCurve.R")
source("functions/mdMetrics.R")
source("functions/plotPCA.R")
source("functions/timer.R")
source("functions/color.R")
source("functions/splitData.R")

subfolder = "11_Adversarial_Network/"
plots = paste0("plots/", subfolder)
if(!dir.exists(plots)) dir.create(plots)
models = paste0("models/", subfolder)
if(!dir.exists(models)) dir.create(models)
baked = paste0("baked/", subfolder)
if(!dir.exists(baked)) dir.create(baked)
recipes = paste0("recipes/", subfolder)
if(!dir.exists(recipes)) dir.create(recipes)

